# Generated by Django 5.1.2 on 2025-12-03 00:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('scores', 'Scores TERAS'), ('reports', 'Rapports'), ('regions', 'Régions'), ('sectors', 'Secteurs'), ('alerts', 'Alertes'), ('enterprise', 'Entreprises'), ('general', 'Général')], max_length=20, verbose_name='Catégorie')),
                ('question', models.TextField(verbose_name='Question')),
                ('suggested_response', models.TextField(verbose_name='Réponse suggérée')),
                ('keywords', models.JSONField(default=list, help_text='Mots-clés pour la détection', verbose_name='Mots-clés')),
                ('usage_count', models.IntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Question fréquente',
                'verbose_name_plural': 'Questions fréquentes',
                'ordering': ['-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('government', 'Gouvernement'), ('admin', 'Administration'), ('enterprise', 'Entreprise'), ('individual', 'Individuel')], default='government', max_length=20, verbose_name='Contexte')),
                ('user_message', models.TextField(verbose_name='Message utilisateur')),
                ('assistant_response', models.TextField(verbose_name='Réponse assistant')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Horodatage')),
                ('session_id', models.CharField(blank=True, help_text='Identifiant de la session de conversation', max_length=100, null=True, verbose_name='ID de session')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Tokens utilisés')),
                ('model_version', models.CharField(default='claude-sonnet-4', max_length=50, verbose_name='Version du modèle')),
                ('response_time_ms', models.IntegerField(default=0, verbose_name='Temps de réponse (ms)')),
                ('user_feedback', models.IntegerField(blank=True, choices=[(1, 'Mauvais'), (2, 'Moyen'), (3, 'Bon'), (4, 'Très bon'), (5, 'Excellent')], null=True, verbose_name='Feedback utilisateur')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires sur la conversation', verbose_name='Métadonnées')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Log de conversation',
                'verbose_name_plural': 'Logs de conversations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], verbose_name='Note')),
                ('is_accurate', models.BooleanField(default=True, verbose_name='Réponse précise')),
                ('is_helpful', models.BooleanField(default=True, verbose_name='Réponse utile')),
                ('is_clear', models.BooleanField(default=True, verbose_name='Réponse claire')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('chat_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_feedback', to='chat.chatlog', verbose_name='Log de conversation')),
            ],
            options={
                'verbose_name': 'Feedback détaillé',
                'verbose_name_plural': 'Feedbacks détaillés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='ID de session')),
                ('context', models.CharField(choices=[('government', 'Gouvernement'), ('admin', 'Administration'), ('enterprise', 'Entreprise'), ('individual', 'Individuel')], default='government', max_length=20, verbose_name='Contexte')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Début de session')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Session active')),
                ('total_messages', models.IntegerField(default=0, verbose_name='Total de messages')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='Total de tokens')),
                ('summary', models.TextField(blank=True, verbose_name='Résumé de la session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session de chat',
                'verbose_name_plural': 'Sessions de chat',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddIndex(
            model_name='chatlog',
            index=models.Index(fields=['user', '-timestamp'], name='chat_chatlo_user_id_ab7537_idx'),
        ),
        migrations.AddIndex(
            model_name='chatlog',
            index=models.Index(fields=['context', '-timestamp'], name='chat_chatlo_context_e3a89d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatlog',
            index=models.Index(fields=['session_id'], name='chat_chatlo_session_f9727c_idx'),
        ),
    ]
