# Generated by Django 6.0.1 on 2026-01-18 03:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('seed', 'SEED - Test/Urgence (14-30j)'), ('starter', 'STARTER - Trésorerie (1-3 mois)'), ('growth', 'GROWTH - Stock/Équipement (3-6 mois)'), ('pro', 'PRO - Expansion (6-24 mois)')], max_length=20)),
                ('description', models.TextField()),
                ('min_score', models.IntegerField(help_text='Score TERAS minimum requis', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('max_score', models.IntegerField(default=1000, help_text='Score TERAS maximum (pour cibler une tranche)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_duration_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_duration_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('interest_rate_min', models.DecimalField(decimal_places=2, help_text='Taux minimum annuel (%)', max_digits=5)),
                ('interest_rate_max', models.DecimalField(decimal_places=2, help_text='Taux maximum annuel (%)', max_digits=5)),
                ('guarantees_required', models.BooleanField(default=False)),
                ('requires_coempruntor', models.BooleanField(default=False, verbose_name='Co-emprunteur requis')),
                ('requires_collateral', models.BooleanField(default=False, verbose_name='Gage matériel requis')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Conditions additionnelles (JSON)')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit de crédit',
                'verbose_name_plural': 'Produits de crédit',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('purpose', models.TextField(help_text='Motif du crédit')),
                ('monthly_income_declared', models.DecimalField(blank=True, decimal_places=2, help_text='Revenus mensuels déclarés', max_digits=12, null=True)),
                ('crm_calculated', models.DecimalField(decimal_places=2, help_text='CRM (30% revenus nets) calculé', max_digits=12)),
                ('teras_score_at_request', models.IntegerField(default=0, help_text='Score TERAS au moment de la demande')),
                ('teras_band_at_request', models.CharField(blank=True, help_text='Bande de score (A+, A, B, C, D, E)', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('under_review', "En cours d'examen"), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('accepted', "Accepté par l'utilisateur"), ('disbursed', 'Décaissé'), ('active', 'Actif'), ('completed', 'Complété'), ('defaulted', 'En défaut'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interest_rate_approved', models.DecimalField(blank=True, decimal_places=2, help_text='Taux annuel approuvé (%)', max_digits=5, null=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Coût total (capital + intérêts)', max_digits=12, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('ai_recommendation', models.JSONField(blank=True, default=dict, help_text='Recommandation IA/Algorithme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credit.creditproduct')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_credits', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de crédit',
                'verbose_name_plural': 'Demandes de crédit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_payments_made', models.IntegerField(default=0)),
                ('on_time_payments', models.IntegerField(default=0)),
                ('late_payments', models.IntegerField(default=0)),
                ('missed_payments', models.IntegerField(default=0)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_late_fees', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('average_payment_delay_days', models.IntegerField(default=0, help_text='Retard moyen en jours')),
                ('max_payment_delay_days', models.IntegerField(default=0, help_text='Retard maximum en jours')),
                ('was_completed', models.BooleanField(default=False)),
                ('was_defaulted', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('behavior_score', models.IntegerField(default=0, help_text='Score de comportement de remboursement', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_history', to=settings.AUTH_USER_MODEL)),
                ('credit_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='credit.creditrequest')),
            ],
            options={
                'verbose_name': 'Historique de crédit',
                'verbose_name_plural': 'Historiques de crédit',
            },
        ),
        migrations.CreateModel(
            name='CreditGuarantee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guarantee_type', models.CharField(choices=[('coempruntor', 'Co-emprunteur/Caution'), ('vehicle', 'Véhicule/Moto'), ('land', 'Terrain/Parcelle'), ('equipment', 'Équipement/Matériel'), ('stock', 'Stock/Marchandise'), ('other', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('estimated_value', models.DecimalField(decimal_places=2, help_text='Valeur estimée en CDF', max_digits=12)),
                ('documents', models.JSONField(blank=True, default=list, help_text='URLs des documents (photos, attestations)')),
                ('status', models.CharField(choices=[('pending', 'En attente de vérification'), ('verified', 'Vérifiée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_guarantees', to=settings.AUTH_USER_MODEL)),
                ('credit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='credit.creditrequest')),
            ],
            options={
                'verbose_name': 'Garantie',
                'verbose_name_plural': 'Garanties',
            },
        ),
        migrations.CreateModel(
            name='CreditPaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.IntegerField(help_text="Numéro d'échéance (1, 2, 3...)")),
                ('due_date', models.DateField(help_text="Date d'échéance")),
                ('principal_amount', models.DecimalField(decimal_places=2, help_text='Part du capital', max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, help_text='Part des intérêts', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Montant total à payer', max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, help_text='Solde restant après ce paiement', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('late', 'Retard'), ('missed', 'Manqué')], default='pending', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Pénalités de retard', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='credit.creditrequest')),
            ],
            options={
                'verbose_name': 'Échéance de paiement',
                'verbose_name_plural': 'Échéancier de paiement',
                'ordering': ['credit_request', 'payment_number'],
                'unique_together': {('credit_request', 'payment_number')},
            },
        ),
    ]
