# Generated by Django 5.1.2 on 2025-12-23 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegislationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titre')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('type', models.CharField(choices=[('law', 'Loi'), ('regulation', 'Règlement'), ('directive', 'Directive'), ('circular', 'Circulaire')], max_length=20, verbose_name='Type')),
                ('category', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('country', models.CharField(choices=[('CEMAC', 'CEMAC (Communautaire)'), ('CM', 'Cameroun'), ('CF', 'Centrafrique'), ('CG', 'Congo'), ('GA', 'Gabon'), ('GQ', 'Guinée Équatoriale'), ('TD', 'Tchad')], max_length=10, verbose_name='Pays')),
                ('publication_date', models.DateField(verbose_name='Date de publication')),
                ('effective_date', models.DateField(verbose_name="Date d'entrée en vigueur")),
                ('summary', models.TextField(verbose_name='Résumé')),
                ('full_text', models.TextField(blank=True, null=True, verbose_name='Texte intégral')),
                ('file', models.FileField(blank=True, null=True, upload_to='legislation/%Y/%m/', verbose_name='Fichier')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='Type MIME')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut')),
                ('ai_analysis', models.JSONField(blank=True, null=True, verbose_name='Analyse IA')),
                ('ai_analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date analyse IA')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Texte extrait')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legislation_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document de législation',
                'verbose_name_plural': 'Documents de législation',
                'db_table': 'legislation_documents',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='LegislationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='legislation.legislationdocument')),
            ],
            options={
                'db_table': 'legislation_comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
