# Generated by Django 6.0.4 on 2026-04-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislationdocument',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AlterField(
            model_name='legislationcomment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='legislationdocument',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legislationdocument',
            name='ai_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legislationdocument',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='legislationdocument',
            name='country',
            field=models.CharField(choices=[('CEMAC', 'CEMAC'), ('CM', 'Cameroun'), ('CF', 'Centrafrique'), ('CG', 'Congo'), ('GA', 'Gabon'), ('GQ', 'Guinée Équatoriale'), ('TD', 'Tchad')], max_length=10),
        ),
        migrations.AlterField(
            model_name='legislationdocument',
            name='effective_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='legislationdocument',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='legislationdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='legislation/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='legislationdocument',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legislationdocument',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='legislationdocument',
            name='full_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legislationdocument',
            name='publication_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='legislationdocument',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='legislationdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('archived', 'Archivé')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='legislationdocument',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='legislationdocument',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='legislationdocument',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='legislationdocument',
            name='type',
            field=models.CharField(choices=[('law', 'Loi'), ('regulation', 'Règlement'), ('directive', 'Directive'), ('circular', 'Circulaire')], max_length=20),
        ),
    ]
