# Generated by Django 5.1.2 on 2025-12-28 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titre')),
                ('document_type', models.CharField(choices=[('legislation', 'Législation'), ('documentation', 'Documentation'), ('faq', 'FAQ'), ('case_study', "Cas d'usage"), ('policy', 'Politique'), ('guide', 'Guide')], max_length=20, verbose_name='Type de document')),
                ('source', models.CharField(blank=True, help_text='URL ou référence source', max_length=500, verbose_name='Source')),
                ('content', models.TextField(verbose_name='Contenu texte')),
                ('content_hash', models.CharField(help_text='SHA256 hash pour déduplication', max_length=64, unique=True, verbose_name='Hash contenu')),
                ('extracted_from', models.CharField(blank=True, help_text='Fichier original si applicable', max_length=500, verbose_name='Extrait de')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('indexing', 'Indexation en cours'), ('indexed', 'Indexé'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut indexation')),
                ('vector_id', models.CharField(blank=True, help_text='ID du document dans ChromaDB', max_length=100, null=True, verbose_name='ID dans vector store')),
                ('chunk_count', models.IntegerField(default=0, help_text='Nombre de morceaux créés', verbose_name='Nombre de chunks')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Tags, catégories, etc.', verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'indexation")),
                ('indexed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indexed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document indexé',
                'verbose_name_plural': 'Documents indexés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('teras_scoring', 'TERAS Scoring'), ('legislation', 'Législation CEMAC'), ('compliance', 'Conformité'), ('fiscal', 'Fiscalité'), ('procedures', 'Procédures'), ('faq', 'FAQ'), ('glossary', 'Glossaire')], max_length=50, verbose_name='Catégorie')),
                ('title', models.CharField(max_length=500, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('keywords', models.JSONField(default=list, verbose_name='Mots-clés')),
                ('priority', models.IntegerField(default=0, help_text='Plus élevé = plus important', verbose_name='Priorité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indexed_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_entries', to='ai.indexeddocument')),
            ],
            options={
                'verbose_name': 'Entrée base de connaissances',
                'verbose_name_plural': 'Base de connaissances',
                'ordering': ['-priority', 'category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RAGQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='Requête')),
                ('documents_found', models.IntegerField(default=0, verbose_name='Documents trouvés')),
                ('documents_used', models.IntegerField(default=0, verbose_name='Documents utilisés')),
                ('response', models.TextField(blank=True, verbose_name='Réponse générée')),
                ('response_time_ms', models.IntegerField(default=0, verbose_name='Temps de réponse (ms)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Similarité scores, sources, etc.', verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requête RAG',
                'verbose_name_plural': 'Requêtes RAG',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='indexeddocument',
            index=models.Index(fields=['status', '-created_at'], name='ai_indexedd_status_201019_idx'),
        ),
        migrations.AddIndex(
            model_name='indexeddocument',
            index=models.Index(fields=['document_type', '-created_at'], name='ai_indexedd_documen_51991e_idx'),
        ),
        migrations.AddIndex(
            model_name='indexeddocument',
            index=models.Index(fields=['content_hash'], name='ai_indexedd_content_3db177_idx'),
        ),
    ]
