# Generated by Django 6.0.1 on 2026-01-09 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexeddocument',
            name='chunk_count',
            field=models.IntegerField(default=0, verbose_name='Nombre de chunks'),
        ),
        migrations.AlterField(
            model_name='indexeddocument',
            name='document_type',
            field=models.CharField(choices=[('legislation', 'Législation'), ('documentation', 'Documentation'), ('faq', 'FAQ'), ('case_study', "Cas d'usage"), ('policy', 'Politique'), ('guide', 'Guide'), ('general', 'Général')], default='general', max_length=20, verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='indexeddocument',
            name='extracted_from',
            field=models.CharField(blank=True, default='', help_text='Fichier original si applicable', max_length=500, verbose_name='Extrait de'),
        ),
        migrations.AlterField(
            model_name='indexeddocument',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Métadonnées'),
        ),
        migrations.AlterField(
            model_name='indexeddocument',
            name='source',
            field=models.CharField(blank=True, default='', help_text='URL ou référence source', max_length=500, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='indexeddocument',
            name='vector_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ID dans vector store'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='ragquery',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Métadonnées'),
        ),
        migrations.AlterField(
            model_name='ragquery',
            name='response',
            field=models.TextField(blank=True, default='', verbose_name='Réponse générée'),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Nouvelle conversation', max_length=255)),
                ('context_type', models.CharField(default='general', max_length=50)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Chat IA',
                'verbose_name_plural': 'Sessions Chat IA',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant'), ('system', 'Système')], max_length=20)),
                ('content', models.TextField()),
                ('sources', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.chatsession')),
            ],
            options={
                'verbose_name': 'Message Chat IA',
                'verbose_name_plural': 'Messages Chat IA',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('collection', models.CharField(db_index=True, max_length=100)),
                ('content', models.TextField()),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('source', models.CharField(blank=True, default='', max_length=500)),
                ('embedding', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Embedding',
                'verbose_name_plural': 'Document Embeddings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['collection', 'created_at'], name='ai_document_collect_68cbee_idx'), models.Index(fields=['content_hash'], name='ai_document_content_20f253_idx')],
            },
        ),
    ]
