# Generated by Django 6.0.4 on 2026-04-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_indexeddocument_chunk_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentembedding',
            name='embedding',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
