# Generated by Django 5.1.2 on 2025-11-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='scorehistory',
            options={},
        ),
        migrations.RenameField(
            model_name='scorehistory',
            old_name='actifs',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='scorehistory',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='scorehistory',
            name='epargne',
        ),
        migrations.RemoveField(
            model_name='scorehistory',
            name='revenus',
        ),
        migrations.RemoveField(
            model_name='scorehistory',
            name='score_total',
        ),
        migrations.RemoveField(
            model_name='scorehistory',
            name='social',
        ),
        migrations.RemoveField(
            model_name='scorehistory',
            name='transactions',
        ),
    ]
