# Generated by Django 5.1.2 on 2025-11-21 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_alter_scorehistory_user_creditscore_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditscore',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='scorehistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Score histories'},
        ),
        migrations.AddField(
            model_name='scorehistory',
            name='actifs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scorehistory',
            name='breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scorehistory',
            name='detail',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scorehistory',
            name='epargne',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scorehistory',
            name='profile_type',
            field=models.CharField(default='basic', max_length=50),
        ),
        migrations.AddField(
            model_name='scorehistory',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scorehistory',
            name='revenus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scorehistory',
            name='score_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scorehistory',
            name='social',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scorehistory',
            name='transactions',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scorehistory',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scorehistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
