# Generated by Django 5.1.2 on 2025-12-10 02:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_alter_creditscore_options_alter_scorehistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_version', models.CharField(default='1.0.0', max_length=20)),
                ('environment', models.CharField(default='production', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('scoring_profile', models.CharField(default='basic', max_length=20)),
                ('scoring_region', models.CharField(default='CEMAC', max_length=50)),
                ('scoring_country', models.CharField(default='Congo', max_length=50)),
                ('alerts_enabled', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('threshold_low_score', models.IntegerField(default=400)),
                ('threshold_high_risk', models.IntegerField(default=300)),
                ('api_rate_limit', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Government Settings',
                'db_table': 'government_settings',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('kinshasa', 'Kinshasa'), ('lubumbashi', 'Lubumbashi'), ('goma', 'Goma'), ('kisangani', 'Kisangani'), ('mbuji-mayi', 'Mbuji-Mayi'), ('kananga', 'Kananga'), ('bukavu', 'Bukavu'), ('matadi', 'Matadi'), ('kikwit', 'Kikwit'), ('mbandaka', 'Mbandaka')], max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('population', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('avg_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('gdp', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unemployment_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'government_regions',
                'ordering': ['-avg_score'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('agriculture', 'Agriculture'), ('industrie', 'Industrie'), ('services', 'Services'), ('commerce', 'Commerce'), ('sante', 'Santé'), ('education', 'Éducation'), ('transport', 'Transport'), ('technologie', 'Technologie'), ('tourisme', 'Tourisme'), ('energie', 'Énergie')], max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('total_enterprises', models.IntegerField(default=0)),
                ('avg_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('growth_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gdp_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('employment', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'government_sectors',
                'ordering': ['-avg_score'],
            },
        ),
        migrations.CreateModel(
            name='GovernmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('annual', 'Annuel'), ('regional', 'Régional'), ('sectoral', 'Sectoriel'), ('custom', 'Personnalisé')], max_length=20)),
                ('status', models.CharField(choices=[('generating', 'En cours de génération'), ('ready', 'Prêt'), ('failed', 'Échec')], default='generating', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/government/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_count', models.IntegerField(default=0)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='government_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'government_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('score_calculated', 'Score calculé'), ('user_registered', 'Utilisateur inscrit'), ('enterprise_registered', 'Entreprise inscrite'), ('alert_created', 'Alerte créée'), ('report_generated', 'Rapport généré')], max_length=50)),
                ('user_type', models.CharField(blank=True, max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoring.region')),
            ],
            options={
                'db_table': 'government_activity_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='government__action_625be4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critique'), ('high', 'Élevée'), ('medium', 'Moyenne'), ('low', 'Faible')], default='medium', max_length=20)),
                ('category', models.CharField(choices=[('economic', 'Économique'), ('fiscal', 'Fiscal'), ('social', 'Social'), ('security', 'Sécurité'), ('infrastructure', 'Infrastructure')], default='economic', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Prise en compte'), ('resolved', 'Résolue')], default='active', max_length=20)),
                ('impact_score', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('affected_users', models.IntegerField(default=0)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='scoring.region')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='scoring.sector')),
            ],
            options={
                'db_table': 'government_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', 'status'], name='government__severit_509b3d_idx'), models.Index(fields=['category'], name='government__categor_47388d_idx')],
            },
        ),
    ]
