# Generated by Django 5.1.2 on 2025-12-12 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_governmentsettings_region_sector_governmentreport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='region',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='region',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='governmentreport',
            name='generated_by',
        ),
        migrations.DeleteModel(
            name='GovernmentSettings',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.DeleteModel(
            name='GovernmentReport',
        ),
    ]
