# Generated by Django 5.1.2 on 2025-12-30 01:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0006_remove_activitylog_region_remove_activitylog_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('real_estate', 'Immobilier'), ('vehicle', 'Véhicule'), ('equipment', 'Équipement'), ('investment', 'Investissement'), ('crypto', 'Crypto-monnaie'), ('other', 'Autre')], max_length=50, verbose_name='Type')),
                ('declared_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valeur déclarée')),
                ('verified_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valeur vérifiée')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Actif',
                'verbose_name_plural': 'Actifs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('salary', 'Salaire'), ('business', 'Activité commerciale'), ('rental', 'Revenus locatifs'), ('investment', 'Investissements'), ('pension', 'Pension'), ('other', 'Autre')], max_length=50, verbose_name='Source')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant mensuel')),
                ('verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date vérification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Revenu',
                'verbose_name_plural': 'Revenus',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('transactions', 'Transactions'), ('epargne', 'Épargne'), ('revenus', 'Revenus'), ('actifs', 'Actifs'), ('social', 'Social'), ('general', 'Général')], max_length=50, verbose_name='Catégorie')),
                ('priority', models.CharField(choices=[('high', 'Haute'), ('medium', 'Moyenne'), ('low', 'Basse')], default='medium', max_length=20, verbose_name='Priorité')),
                ('impact', models.CharField(blank=True, help_text='Ex: +15 points', max_length=100, verbose_name='Impact')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Complétée')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date complétion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerasScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_id', models.CharField(editable=False, max_length=100, unique=True, verbose_name='ID Score')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Score Total')),
                ('band', models.CharField(choices=[('A', 'Excellent (900-1000)'), ('B', 'Très bon (750-899)'), ('C', 'Bon (600-749)'), ('D', 'Moyen (400-599)'), ('E', 'Faible (0-399)')], max_length=1, verbose_name='Bande')),
                ('T', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Transactions (T)')),
                ('E', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Épargne (E)')),
                ('R', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Revenus (R)')),
                ('A', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Actifs (A)')),
                ('S', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Social (S)')),
                ('model_version', models.CharField(default='basic-1.0.0', max_length=20, verbose_name='Version du modèle')),
                ('computed_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de calcul')),
                ('reason_codes', models.JSONField(blank=True, default=list, verbose_name='Codes de raison')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Données brutes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teras_scores', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Score TERAS',
                'verbose_name_plural': 'Scores TERAS',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['user', '-computed_at'], name='scoring_ter_user_id_293ebf_idx'), models.Index(fields=['band'], name='scoring_ter_band_755e79_idx'), models.Index(fields=['score'], name='scoring_ter_score_2d9f87_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('credit', 'Crédit'), ('debit', 'Débit')], max_length=10, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('currency', models.CharField(default='XAF', max_length=3, verbose_name='Devise')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('channel', models.CharField(blank=True, max_length=50, verbose_name='Canal')),
                ('status', models.CharField(choices=[('completed', 'Complétée'), ('pending', 'En attente'), ('failed', 'Échouée'), ('cancelled', 'Annulée')], default='completed', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='scoring_tra_user_id_d47bb2_idx')],
            },
        ),
    ]
