# Generated by Django 5.1.2 on 2025-12-31 01:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0007_asset_income_recommendation_terasscore_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='scorehistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='terasscore',
            options={'ordering': ['-created_at'], 'verbose_name': 'Score TERAS', 'verbose_name_plural': 'Scores TERAS'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='terasscore',
            name='scoring_ter_user_id_293ebf_idx',
        ),
        migrations.RemoveIndex(
            model_name='terasscore',
            name='scoring_ter_band_755e79_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='scoring_tra_user_id_d47bb2_idx',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='verified_value',
        ),
        migrations.RemoveField(
            model_name='income',
            name='monthly_amount',
        ),
        migrations.RemoveField(
            model_name='income',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='scorehistory',
            name='actifs',
        ),
        migrations.RemoveField(
            model_name='scorehistory',
            name='breakdown',
        ),
        migrations.RemoveField(
            model_name='scorehistory',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='scorehistory',
            name='epargne',
        ),
        migrations.RemoveField(
            model_name='scorehistory',
            name='profile_type',
        ),
        migrations.RemoveField(
            model_name='scorehistory',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='scorehistory',
            name='revenus',
        ),
        migrations.RemoveField(
            model_name='scorehistory',
            name='score_total',
        ),
        migrations.RemoveField(
            model_name='scorehistory',
            name='social',
        ),
        migrations.RemoveField(
            model_name='scorehistory',
            name='transactions',
        ),
        migrations.RemoveField(
            model_name='terasscore',
            name='A',
        ),
        migrations.RemoveField(
            model_name='terasscore',
            name='E',
        ),
        migrations.RemoveField(
            model_name='terasscore',
            name='R',
        ),
        migrations.RemoveField(
            model_name='terasscore',
            name='S',
        ),
        migrations.RemoveField(
            model_name='terasscore',
            name='T',
        ),
        migrations.RemoveField(
            model_name='terasscore',
            name='band',
        ),
        migrations.RemoveField(
            model_name='terasscore',
            name='computed_at',
        ),
        migrations.RemoveField(
            model_name='terasscore',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='terasscore',
            name='score_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tx_type',
        ),
        migrations.AddField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='income',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='terasscore',
            name='assets_score',
            field=models.IntegerField(default=0, help_text='Score Actifs (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='terasscore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terasscore',
            name='income_score',
            field=models.IntegerField(default=0, help_text='Score Revenus (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='terasscore',
            name='level',
            field=models.CharField(choices=[('debutant', 'Débutant'), ('bronze', 'Bronze'), ('argent', 'Argent'), ('or', 'Or'), ('diamant', 'Diamant')], default='debutant', max_length=20),
        ),
        migrations.AddField(
            model_name='terasscore',
            name='savings_score',
            field=models.IntegerField(default=0, help_text='Score Épargne (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='terasscore',
            name='social_score',
            field=models.IntegerField(default=0, help_text='Score Social/Stabilité (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='terasscore',
            name='transactions_score',
            field=models.IntegerField(default=0, help_text='Score Transactions (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='terasscore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='terasscore',
            name='weight_a',
            field=models.FloatField(default=0.2, help_text='Poids Actifs'),
        ),
        migrations.AddField(
            model_name='terasscore',
            name='weight_e',
            field=models.FloatField(default=0.18, help_text='Poids Épargne'),
        ),
        migrations.AddField(
            model_name='terasscore',
            name='weight_r',
            field=models.FloatField(default=0.22, help_text='Poids Revenus'),
        ),
        migrations.AddField(
            model_name='terasscore',
            name='weight_s',
            field=models.FloatField(default=0.12, help_text='Poids Social'),
        ),
        migrations.AddField(
            model_name='terasscore',
            name='weight_t',
            field=models.FloatField(default=0.28, help_text='Poids Transactions'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Crédit'), ('debit', 'Débit')], default='credit', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('real_estate', 'Immobilier'), ('vehicle', 'Véhicule'), ('equipment', 'Équipement'), ('savings', 'Épargne'), ('other', 'Autre')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='declared_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='income',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(default='Non spécifié', max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='income',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='category',
            field=models.CharField(choices=[('transactions', 'Transactions'), ('epargne', 'Épargne'), ('revenus', 'Revenus'), ('actifs', 'Actifs'), ('social', 'Social')], default='transactions', max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='impact',
            field=models.CharField(default='+0 points', help_text='Ex: +15 points', max_length=50),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='priority',
            field=models.CharField(choices=[('high', 'Haute'), ('medium', 'Moyenne'), ('low', 'Basse')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='title',
            field=models.CharField(default='Recommandation', max_length=200),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='terasscore',
            name='model_version',
            field=models.CharField(default='teras-basic-1.0', help_text="Version de l'algorithme utilisé", max_length=50),
        ),
        migrations.AlterField(
            model_name='terasscore',
            name='reason_codes',
            field=models.JSONField(blank=True, default=list, help_text='Codes de raison expliquant le score (SHAP)'),
        ),
        migrations.AlterField(
            model_name='terasscore',
            name='score',
            field=models.IntegerField(default=0, help_text='Score TERAS global (0-1000 points)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='terasscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teras_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='channel',
            field=models.CharField(default='mobile_money', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='terasscore',
            index=models.Index(fields=['user', '-created_at'], name='scoring_ter_user_id_62355c_idx'),
        ),
        migrations.AddIndex(
            model_name='terasscore',
            index=models.Index(fields=['level'], name='scoring_ter_level_c69906_idx'),
        ),
    ]
