# Generated by Django 5.1.2 on 2026-01-05 06:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0008_alter_asset_options_alter_income_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to='user_documents/%Y/%m/')),
                ('filename', models.CharField(help_text='Nom original du fichier', max_length=255)),
                ('file_size', models.IntegerField(default=0, help_text='Taille en octets')),
                ('mime_type', models.CharField(default='application/octet-stream', help_text='Type MIME du fichier', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploadé'), ('processing', "En cours d'analyse"), ('parsed', 'Analysé'), ('failed', 'Échec')], default='uploaded', max_length=20)),
                ('category', models.CharField(choices=[('general', 'Général'), ('bank_statement', 'Relevé bancaire'), ('payslip', 'Fiche de paie'), ('invoice', 'Facture'), ('proof_asset', "Justificatif d'actif"), ('identity', "Pièce d'identité"), ('tax_document', 'Document fiscal'), ('other', 'Autre')], default='general', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags pour classification automatique')),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Données extraites : transactions, revenus, actifs, etc.')),
                ('ai_analysis', models.JSONField(blank=True, default=dict, help_text='Analyse IA : insights, recommandations, impact score')),
                ('confidence', models.FloatField(default=0.0, help_text="Confiance de l'analyse IA (0-1)", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('processed_at', models.DateTimeField(blank=True, help_text='Date de fin de traitement IA', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text="Message d'erreur en cas d'échec")),
            ],
            options={
                'verbose_name': 'Document utilisateur',
                'verbose_name_plural': 'Documents utilisateur',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='terasscore',
            name='is_simulated',
            field=models.BooleanField(default=False, help_text='True si le score est une simulation'),
        ),
        migrations.AddField(
            model_name='terasscore',
            name='source',
            field=models.CharField(choices=[('simulation', 'Simulation'), ('computed', 'Calcul manuel'), ('document', 'Analyse document'), ('api', 'API externe'), ('system', 'Système')], default='system', help_text='Source du calcul de score', max_length=20),
        ),
        migrations.AddIndex(
            model_name='terasscore',
            index=models.Index(fields=['is_simulated'], name='scoring_ter_is_simu_3658fd_idx'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='generated_score',
            field=models.ForeignKey(blank=True, help_text='Score TERAS généré à partir de ce document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to='scoring.terasscore'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userdocument',
            index=models.Index(fields=['user', '-uploaded_at'], name='scoring_use_user_id_4c0771_idx'),
        ),
        migrations.AddIndex(
            model_name='userdocument',
            index=models.Index(fields=['status'], name='scoring_use_status_1ff38f_idx'),
        ),
        migrations.AddIndex(
            model_name='userdocument',
            index=models.Index(fields=['category'], name='scoring_use_categor_cd5856_idx'),
        ),
    ]
