# Generated by Django 6.0.1 on 2026-01-19 18:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0011_supportticket_ticketmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmessage',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='sender',
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Actif', 'verbose_name_plural': 'Actifs'},
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='declared_value',
            new_name='estimated_value',
        ),
        migrations.RemoveField(
            model_name='income',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='income',
            name='period_start',
        ),
        migrations.AddField(
            model_name='income',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Revenu récurrent (salaire, rente, etc.)'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('immobilier', 'Immobilier'), ('vehicule', 'Véhicule'), ('terrain', 'Terrain'), ('equipement', 'Équipement professionnel'), ('epargne', 'Épargne/Investissement'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='verified',
            field=models.BooleanField(default=False, help_text='Actif vérifié par documents'),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(default='Autre', max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='verified',
            field=models.BooleanField(default=False, help_text='Revenu vérifié par documents'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='document_type',
            field=models.CharField(choices=[('id_card', "Carte d'identité"), ('passport', 'Passeport'), ('residence_permit', 'Titre de séjour'), ('utility_bill', 'Facture de services publics'), ('bank_statement', 'Relevé bancaire'), ('driver_license', 'Permis de conduire'), ('other', 'Autre')], default='id_card', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='SocialReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0, help_text='Note moyenne (0-5 étoiles)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('reviews_count', models.IntegerField(default=0, help_text="Nombre d'avis reçus")),
                ('positive_feedbacks', models.IntegerField(default=0, help_text='Nombre de retours positifs')),
                ('negative_feedbacks', models.IntegerField(default=0, help_text='Nombre de retours négatifs')),
                ('community_participation', models.IntegerField(default=0, help_text='Score de participation communautaire (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_reputation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réputation Sociale',
                'verbose_name_plural': 'Réputations Sociales',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='SupportTicket',
        ),
        migrations.DeleteModel(
            name='TicketMessage',
        ),
    ]
