# Generated by Django 6.0.1 on 2026-03-25 18:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0012_remove_ticketmessage_ticket_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('personal', 'Crédit Personnel'), ('auto', 'Crédit Auto'), ('immobilier', 'Crédit Immobilier'), ('pme', 'Crédit PME'), ('agricole', 'Crédit Agricole'), ('education', 'Crédit Éducation'), ('other', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('min_duration_months', models.IntegerField()),
                ('max_duration_months', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_score_required', models.IntegerField(default=400, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('max_age', models.IntegerField(default=65)),
                ('min_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('applications_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bank_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='CD', max_length=2)),
                ('occupation', models.CharField(max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('teras_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('teras_band', models.CharField(blank=True, max_length=5)),
                ('active_loans_count', models.IntegerField(default=0)),
                ('total_borrowed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu')], default='active', max_length=20)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankEnterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('tax_id', models.CharField(max_length=50, unique=True)),
                ('enterprise_type', models.CharField(choices=[('pme', 'PME'), ('grande_entreprise', 'Grande Entreprise'), ('startup', 'Startup'), ('association', 'Association/ONG')], max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='CD', max_length=2)),
                ('annual_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('employees_count', models.IntegerField(default=0)),
                ('teras_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('teras_band', models.CharField(blank=True, max_length=5)),
                ('active_loans_count', models.IntegerField(default=0)),
                ('total_borrowed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu')], default='active', max_length=20)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_enterprise_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_enterprises',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('applicant_type', models.CharField(choices=[('individual', 'Particulier'), ('enterprise', 'Entreprise')], max_length=20)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duration_months', models.IntegerField()),
                ('purpose', models.TextField()),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_repayment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('teras_score_at_application', models.IntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('review', 'En révision'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('disbursed', 'Décaissé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scoring.bankclient')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scoring.bankenterprise')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='scoring.financialproduct')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
