# Generated by Django 6.0.1 on 2026-04-03 19:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0014_governmentsettings_region_sector_governmentreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_rate', models.DecimalField(decimal_places=2, default=0, help_text='Taux de conformité global (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_tax_filing', models.DateField(blank=True, help_text='Date dernière déclaration fiscale', null=True)),
                ('missing_declarations', models.JSONField(default=list, help_text='Liste des déclarations manquantes')),
                ('late_payments', models.IntegerField(default=0, help_text='Nombre de paiements en retard')),
                ('penalties', models.DecimalField(decimal_places=2, default=0, help_text='Montant total des pénalités', max_digits=12)),
                ('active_alerts', models.JSONField(default=list, help_text='Alertes actives de conformité')),
                ('recommendations', models.JSONField(default=list, help_text='Recommandations pour améliorer la conformité')),
                ('last_audit_date', models.DateField(blank=True, help_text='Date dernier audit', null=True)),
                ('next_audit_date', models.DateField(blank=True, help_text='Date prochain audit prévu', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.OneToOneField(help_text='Entreprise concernée', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statut de Conformité',
                'verbose_name_plural': 'Statuts de Conformité',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(help_text='Matricule employé', max_length=50, unique=True)),
                ('position', models.CharField(help_text='Poste occupé', max_length=100)),
                ('department', models.CharField(blank=True, help_text='Département', max_length=100)),
                ('hire_date', models.DateField(help_text="Date d'embauche")),
                ('employment_type', models.CharField(choices=[('permanent', 'CDI'), ('contract', 'CDD'), ('intern', 'Stage'), ('temporary', 'Intérimaire')], default='permanent', max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Salaire mensuel brut (optionnel)', max_digits=12, null=True)),
                ('is_local', models.BooleanField(default=True, help_text='Employé recruté localement (impact pilier E)')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('on_leave', 'En congé'), ('terminated', 'Parti')], default='active', max_length=20)),
                ('termination_date', models.DateField(blank=True, help_text='Date de départ si applicable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(help_text='Entreprise employeur', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['-hire_date'],
                'indexes': [models.Index(fields=['enterprise', 'status'], name='scoring_emp_enterpr_1b7ae1_idx'), models.Index(fields=['is_local'], name='scoring_emp_is_loca_38a1f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du client ou raison sociale', max_length=255)),
                ('client_type', models.CharField(choices=[('individual', 'Particulier'), ('pme', 'PME'), ('company', 'Entreprise')], default='individual', max_length=20)),
                ('kyc_id', models.CharField(help_text='Identifiant KYC unique du client', max_length=100, unique=True)),
                ('internal_ref', models.CharField(blank=True, help_text="Référence interne de l'entreprise", max_length=100, null=True)),
                ('teras_score', models.IntegerField(blank=True, help_text='Score TERAS du client (0-1000)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('risk_level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé')], default='medium', help_text='Niveau de risque calculé', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('pending', 'En attente'), ('archived', 'Archivé')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes internes sur le client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(help_text='Entreprise propriétaire de ce dossier', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Entreprise',
                'verbose_name_plural': 'Clients Entreprise',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enterprise', 'status'], name='scoring_ent_enterpr_f85849_idx'), models.Index(fields=['teras_score'], name='scoring_ent_teras_s_d754ab_idx'), models.Index(fields=['risk_level'], name='scoring_ent_risk_le_0fedfd_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tax_filing', 'Déclaration fiscale'), ('balance_sheet', 'Bilan comptable'), ('invoice', 'Facture'), ('payroll', 'Fiche de paie'), ('bank_statement', 'Relevé bancaire'), ('contract', 'Contrat'), ('other', 'Autre')], default='other', max_length=30)),
                ('title', models.CharField(help_text='Titre du document', max_length=255)),
                ('file', models.FileField(help_text='Fichier uploadé', upload_to='enterprise_docs/%Y/%m/')),
                ('period', models.CharField(blank=True, help_text='Période couverte (ex: Q3 2024, Année 2024)', max_length=50)),
                ('period_start', models.DateField(blank=True, help_text='Début de période', null=True)),
                ('period_end', models.DateField(blank=True, help_text='Fin de période', null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('analysis_summary', models.JSONField(blank=True, help_text="Résultat de l'analyse automatique", null=True)),
                ('validation_notes', models.TextField(blank=True, help_text='Notes de validation')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Date de traitement', null=True)),
                ('enterprise', models.ForeignKey(help_text='Entreprise propriétaire', on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Entreprise',
                'verbose_name_plural': 'Documents Entreprise',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['enterprise', 'category'], name='scoring_ent_enterpr_3dda55_idx'), models.Index(fields=['status'], name='scoring_ent_status_81fe7d_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('quarterly', 'Rapport Trimestriel'), ('annual', 'Rapport Annuel'), ('sector_comparison', 'Comparaison Sectorielle'), ('custom', 'Rapport Personnalisé')], default='quarterly', max_length=30)),
                ('title', models.CharField(help_text='Titre du rapport', max_length=255)),
                ('period_start', models.DateField(help_text='Début de période')),
                ('period_end', models.DateField(help_text='Fin de période')),
                ('file', models.FileField(blank=True, help_text='Fichier PDF du rapport', null=True, upload_to='enterprise_reports/%Y/%m/')),
                ('status', models.CharField(choices=[('generating', 'En génération'), ('ready', 'Prêt'), ('failed', 'Échec')], default='generating', max_length=20)),
                ('report_data', models.JSONField(blank=True, help_text='Données brutes du rapport', null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_count', models.IntegerField(default=0, help_text='Nombre de téléchargements')),
                ('enterprise', models.ForeignKey(help_text='Entreprise concernée', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport Entreprise',
                'verbose_name_plural': 'Rapports Entreprise',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['enterprise', 'report_type'], name='scoring_ent_enterpr_aee95a_idx'), models.Index(fields=['status'], name='scoring_ent_status_277503_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Score TERAS Entreprise total', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('breakdown', models.JSONField(help_text='Décomposition détaillée: {T, E, R, A, S}')),
                ('input_data', models.JSONField(blank=True, help_text='Données utilisées pour le calcul', null=True)),
                ('sector', models.CharField(blank=True, help_text="Secteur d'activité", max_length=100)),
                ('sector_average', models.IntegerField(blank=True, help_text='Score moyen du secteur', null=True)),
                ('percentile', models.IntegerField(blank=True, help_text='Percentile dans le secteur', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(help_text='Entreprise évaluée', on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Score TERAS Entreprise',
                'verbose_name_plural': 'Scores TERAS Entreprise',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['enterprise', '-computed_at'], name='scoring_ent_enterpr_0e3063_idx'), models.Index(fields=['score'], name='scoring_ent_score_9666f9_idx')],
            },
        ),
    ]
