# Generated by Django 6.0.4 on 2026-04-16 03:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0015_compliancestatus_employee_enterpriseclient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankclient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Client Banque'},
        ),
        migrations.AlterModelOptions(
            name='bankenterprise',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entreprise Banque'},
        ),
        migrations.AlterModelOptions(
            name='financialproduct',
            options={'ordering': ['min_score_required', 'min_amount'], 'verbose_name': 'Produit Financier'},
        ),
        migrations.RemoveField(
            model_name='bankclient',
            name='national_id',
        ),
        migrations.AddField(
            model_name='bankclient',
            name='niu',
            field=models.CharField(default='TEMP-NIU', help_text='Identifiant unique du citoyen congolais', max_length=50, unique=True, verbose_name="NIU (Numéro d'Identification Universel)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankclient',
            name='teras_account_email',
            field=models.EmailField(blank=True, help_text='Email du compte TERAS auto-créé', max_length=254),
        ),
        migrations.AddField(
            model_name='bankclient',
            name='teras_account_password',
            field=models.CharField(blank=True, help_text='Mot de passe initial (en clair pour remise au client)', max_length=100),
        ),
        migrations.AddField(
            model_name='bankenterprise',
            name='sector',
            field=models.CharField(blank=True, max_length=100, verbose_name="Secteur d'activité"),
        ),
        migrations.AddField(
            model_name='bankenterprise',
            name='teras_account_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='bankenterprise',
            name='teras_account_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='Liste des caractéristiques clés'),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Produit standard pré-configuré'),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='origination_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5, verbose_name='Frais de dossier (%)'),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='requirements',
            field=models.JSONField(blank=True, default=list, help_text='Documents/conditions requis'),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='bankclient',
            name='city',
            field=models.CharField(default='Brazzaville', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankclient',
            name='country',
            field=models.CharField(default='CG', max_length=2),
        ),
        migrations.AlterField(
            model_name='bankclient',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='bankclient',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='bankclient',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='bankclient',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Revenus mensuels (FCFA)'),
        ),
        migrations.AlterField(
            model_name='bankclient',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bankenterprise',
            name='annual_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='CA annuel (FCFA)'),
        ),
        migrations.AlterField(
            model_name='bankenterprise',
            name='city',
            field=models.CharField(default='Brazzaville', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankenterprise',
            name='country',
            field=models.CharField(default='CG', max_length=2),
        ),
        migrations.AlterField(
            model_name='bankenterprise',
            name='enterprise_type',
            field=models.CharField(choices=[('pme', 'PME'), ('grande_entreprise', 'Grande Entreprise'), ('startup', 'Startup'), ('association', 'Association/ONG'), ('cooperative', 'Coopérative')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bankenterprise',
            name='legal_name',
            field=models.CharField(max_length=200, verbose_name='Raison sociale'),
        ),
        migrations.AlterField(
            model_name='bankenterprise',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom commercial'),
        ),
        migrations.AlterField(
            model_name='bankenterprise',
            name='registration_number',
            field=models.CharField(help_text='Registre du Commerce (OHADA)', max_length=50, unique=True, verbose_name='N° RCCM'),
        ),
        migrations.AlterField(
            model_name='bankenterprise',
            name='tax_id',
            field=models.CharField(help_text="Numéro d'Identification Fiscale", max_length=50, unique=True, verbose_name='NIU Entreprise'),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Taux d'intérêt (%/an)"),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant maximum (FCFA)'),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='max_duration_months',
            field=models.IntegerField(verbose_name='Durée max (mois)'),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant minimum (FCFA)'),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='min_duration_months',
            field=models.IntegerField(verbose_name='Durée min (mois)'),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='min_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Revenu minimum (FCFA/mois)'),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='min_score_required',
            field=models.IntegerField(default=400, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Score TERAS minimum'),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='product_type',
            field=models.CharField(choices=[('microcredit', 'Microcrédit / Tontine'), ('personal', 'Crédit Personnel'), ('salary', 'Avance sur Salaire'), ('auto', 'Crédit Auto'), ('immobilier', 'Crédit Immobilier'), ('pme', 'Crédit PME'), ('agricole', 'Crédit Agricole'), ('education', 'Crédit Éducation'), ('epargne', 'Épargne Bloquée'), ('other', 'Autre')], max_length=50),
        ),
    ]
