# Generated by Django 6.0.4 on 2026-04-16 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0016_alter_bankclient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('info', 'Information'), ('offer', 'Offre commerciale'), ('reminder', 'Rappel échéance'), ('alert', 'Alerte compte')], default='info', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sender_name', models.CharField(default='TERAS Banque', max_length=100)),
                ('related_application_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(help_text='Utilisateur TERAS destinataire', on_delete=django.db.models.deletion.CASCADE, related_name='bank_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Banque',
                'ordering': ['-created_at'],
            },
        ),
    ]
