# Generated by Django 6.0.4 on 2026-04-17 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0017_bankmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin — Accès complet'), ('manager', 'Manager — Gestion employés & rapports'), ('analyst', 'Analyst — Consultation & rapports'), ('viewer', 'Viewer — Consultation uniquement')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('bank_enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='scoring.bankenterprise')),
                ('enterprise_user', models.ForeignKey(blank=True, help_text="User propriétaire de l'espace entreprise", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_team_owned', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre équipe',
                'db_table': 'enterprise_team_members',
            },
        ),
    ]
