# Generated by Django 6.0.4 on 2026-04-17 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0018_teammember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_employees', to='scoring.bankenterprise'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, help_text='Email professionnel', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='niu',
            field=models.CharField(blank=True, max_length=50, verbose_name='NIU'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='teras_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_enterprise_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
