# Generated by Django 6.0.4 on 2026-04-20 22:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0019_employee_bank_enterprise_employee_email_employee_niu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('airtel_money', 'Airtel Money'), ('mtn_money', 'MTN Money'), ('zola', 'ZOLA (Portefeuille digital)'), ('orange_money', 'Orange Money'), ('bank_account', 'Compte Bancaire'), ('other', 'Autre')], max_length=30, verbose_name='Opérateur')),
                ('account_type', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_account', 'Compte Bancaire'), ('wallet', 'Portefeuille Digital')], default='mobile_money', max_length=20, verbose_name='Type de compte')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s\\-]{8,20}$', 'Numéro invalide')], verbose_name='Numéro de téléphone')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de compte bancaire (IBAN)')),
                ('account_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du titulaire du compte')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la banque')),
                ('status', models.CharField(choices=[('pending', 'En attente de vérification'), ('verified', 'Vérifié'), ('failed', 'Échec de vérification'), ('syncing', 'Synchronisation en cours'), ('synced', 'Synchronisé')], default='pending', max_length=20, verbose_name='Statut')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Compte principal')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('verification_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code de vérification OTP')),
                ('balance_xaf', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Solde (FCFA)')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière synchronisation')),
                ('transactions_imported', models.IntegerField(default=0, verbose_name='Transactions importées')),
                ('consent_given', models.BooleanField(default=False, verbose_name='Consentement accès données donné')),
                ('consent_at', models.DateTimeField(blank=True, null=True, verbose_name='Date du consentement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Compte lié',
                'verbose_name_plural': 'Comptes liés',
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('user', 'operator', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email du membre')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('interface', models.CharField(choices=[('bank', 'Interface Banque'), ('enterprise', 'Interface Entreprise'), ('government', 'Interface Gouvernement')], max_length=20, verbose_name='Interface concernée')),
                ('role', models.CharField(choices=[('bank_admin', 'Administrateur Banque'), ('bank_analyst', 'Analyste Crédit'), ('bank_agent', 'Agent Commercial'), ('bank_viewer', 'Lecture seule'), ('ent_admin', 'Administrateur'), ('ent_manager', 'Manager'), ('ent_accountant', 'Comptable'), ('ent_hr', 'Ressources Humaines'), ('ent_viewer', 'Lecture seule'), ('gov_admin', 'Administrateur'), ('gov_minister', 'Ministre / Directeur'), ('gov_analyst', 'Analyste'), ('gov_viewer', 'Lecture seule')], max_length=30, verbose_name='Rôle')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('pending', 'Invitation en attente'), ('suspended', 'Suspendu')], default='pending', max_length=20, verbose_name='Statut')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='\n        Exemple:\n        {\n          "can_approve_loans": true,\n          "can_view_clients": true,\n          "can_create_clients": true,\n          "can_edit_clients": false,\n          "can_delete_clients": false,\n          "can_view_analytics": true,\n          "can_export_data": false,\n          "can_manage_team": false,\n          "can_view_documents": true,\n          "can_upload_documents": true,\n          "max_loan_amount": 5000000,\n          "allowed_regions": ["Brazzaville", "Pointe-Noire"]\n        }\n        ', verbose_name='Permissions spécifiques')),
                ('invite_token', models.CharField(blank=True, max_length=64, null=True, verbose_name="Token d'invitation")),
                ('invite_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiration invitation')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation")),
                ('last_active_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière activité')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to=settings.AUTH_USER_MODEL, verbose_name='Institution (compte principal)')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_invitations_sent', to=settings.AUTH_USER_MODEL, verbose_name='Invité par')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur TERAS')),
            ],
            options={
                'verbose_name': 'Membre du personnel',
                'verbose_name_plural': 'Membres du personnel',
                'ordering': ['role', 'last_name', 'first_name'],
                'unique_together': {('institution_user', 'email', 'interface')},
            },
        ),
        migrations.CreateModel(
            name='StaffActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='Action')),
                ('resource', models.CharField(blank=True, max_length=100, verbose_name='Ressource concernée')),
                ('resource_id', models.CharField(blank=True, max_length=50, verbose_name='ID ressource')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='scoring.staffmember', verbose_name='Membre du staff')),
            ],
            options={
                'verbose_name': "Log d'activité staff",
                'verbose_name_plural': "Logs d'activité staff",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID externe (opérateur)')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (FCFA)')),
                ('tx_type', models.CharField(choices=[('credit', 'Crédit (entrée)'), ('debit', 'Débit (sortie)')], max_length=10, verbose_name='Type')),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Solde après transaction')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Catégorie (salaire, loyer, tontine...)')),
                ('is_income', models.BooleanField(default=False)),
                ('applied_to_teras', models.BooleanField(default=False, verbose_name='Appliqué au score TERAS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_transactions', to='scoring.linkedaccount', verbose_name='Compte source')),
            ],
            options={
                'verbose_name': 'Transaction importée',
                'verbose_name_plural': 'Transactions importées',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('linked_account', 'external_id')},
            },
        ),
    ]
