# Generated by Django 6.0.4 on 2026-04-21 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0020_linkedaccount_staffmember_staffactivitylog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankclient',
            name='bank_owner',
            field=models.ForeignKey(blank=True, help_text='Compte banque propriétaire de ce client portefeuille', limit_choices_to={'user_type': 'bank'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_bank_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankenterprise',
            name='bank_owner',
            field=models.ForeignKey(blank=True, help_text='Compte banque propriétaire de cette entreprise portefeuille', limit_choices_to={'user_type': 'bank'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_bank_enterprises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='bank_owner',
            field=models.ForeignKey(blank=True, help_text='Banque propriétaire du produit', limit_choices_to={'user_type': 'bank'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_bank_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='bank_owner',
            field=models.ForeignKey(blank=True, help_text='Banque responsable de cette demande', limit_choices_to={'user_type': 'bank'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_loan_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
