# Generated by Django 5.1.2 on 2025-11-10 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_documents/')),
                ('category', models.CharField(choices=[('bank', 'Relevé bancaire'), ('payslip', 'Bulletin de salaire'), ('other', 'Autre')], default='other', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', help_text='Statut du traitement du document', max_length=20)),
                ('analysis_summary', models.TextField(blank=True, help_text="Résumé de l'analyse effectuée sur ce document")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
