# Generated by Django 5.1.2 on 2025-11-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_uploadeddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('admin', 'Admin'), ('entreprise', 'Entreprise'), ('regional', 'Régional')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='analysis_summary',
            field=models.TextField(blank=True, help_text="Résumé de l'analyse effectuée"),
        ),
    ]
