# Generated by Django 5.1.2 on 2025-11-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Individuel'), ('admin', 'Administrateur'), ('enterprise', 'Entreprise'), ('government', 'Gouvernement')], default='individual', max_length=20, verbose_name='Type de compte'),
        ),
    ]
