# Generated by Django 5.1.2 on 2025-12-08 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_email_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profils'},
        ),
        migrations.AlterModelOptions(
            name='uploadeddocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Pays (code ISO)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Individuel'), ('admin', 'Administrateur'), ('enterprise', 'Entreprise'), ('government', 'Gouvernement'), ('bank', 'Banque')], default='individual', max_length=20, verbose_name='Type de compte'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='analysis_summary',
            field=models.TextField(blank=True, verbose_name="Résumé de l'analyse"),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='category',
            field=models.CharField(choices=[('bank', 'Relevé bancaire'), ('payslip', 'Bulletin de salaire'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file',
            field=models.FileField(upload_to='user_documents/%Y/%m/%d/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('processed', 'Traité'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload"),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
