# Generated by Django 5.1.2 on 2025-12-19 00:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadeddocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Document uploadé', 'verbose_name_plural': 'Documents uploadés'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_registration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro RCCM'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Pays (code ISO)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='employee_count',
            field=models.IntegerField(blank=True, null=True, verbose_name="Nombre d'employés"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_status',
            field=models.CharField(choices=[('not_started', 'Non commencé'), ('pending', 'En attente'), ('incomplete', 'Incomplet'), ('under_review', 'En cours de vérification'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='not_started', max_length=20, verbose_name='Statut KYC'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date vérification KYC'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Région/Département'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Secteur d'activité"),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('national_id', "Carte Nationale d'Identité"), ('passport', 'Passeport'), ('drivers_license', 'Permis de conduire'), ('residence_proof', 'Justificatif de domicile'), ('bank_statement', 'Relevé bancaire'), ('business_registration', 'RCCM'), ('business_statutes', 'Statuts'), ('tax_certificate', 'Certificat fiscal'), ('balance_sheet', 'Bilan comptable'), ('business_plan', "Plan d'affaires"), ('official_mandate', 'Mandat officiel'), ('accreditation', 'Accréditation'), ('government_id', 'Badge gouvernemental'), ('banking_license', 'Licence bancaire'), ('certification', 'Certification'), ('audit_report', "Rapport d'audit"), ('other', 'Autre')], max_length=50, verbose_name='Type de document')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Fichier')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('under_review', 'En cours de vérification'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('flagged', 'Signalé'), ('expired', 'Expiré')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by_admin', models.BooleanField(default=False)),
                ('ai_analyzed', models.BooleanField(default=False)),
                ('ai_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_confidence_score', models.FloatField(blank=True, help_text='Score de confiance IA (0-100)', null=True)),
                ('ai_recommendation', models.CharField(blank=True, choices=[('approve', 'Approuver'), ('reject', 'Rejeter'), ('review', 'Réviser manuellement'), ('request_more', "Demander plus d'info")], max_length=50, null=True)),
                ('ai_analysis_json', models.JSONField(blank=True, help_text="Résultat complet de l'analyse IA", null=True)),
                ('extracted_data', models.JSONField(blank=True, help_text='Données extraites du document', null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('admin_uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LegislationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('CG', 'Congo-Brazzaville'), ('CM', 'Cameroun'), ('GA', 'Gabon'), ('TD', 'Tchad'), ('CF', 'Centrafrique'), ('GQ', 'Guinée Équatoriale')], max_length=2, verbose_name='Pays')),
                ('category', models.CharField(choices=[('kyc', 'KYC/AML'), ('banking', 'Bancaire'), ('business', 'Droit des affaires'), ('tax', 'Fiscalité'), ('labor', 'Droit du travail'), ('compliance', 'Conformité'), ('other', 'Autre')], max_length=50, verbose_name='Catégorie')),
                ('title', models.CharField(max_length=500, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='legislation/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Fichier PDF')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('page_count', models.IntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name="Date d'entrée en vigueur")),
                ('language', models.CharField(default='fr', max_length=2, verbose_name='Langue')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('indexed', models.BooleanField(default=False, verbose_name='Indexé')),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('chunks_count', models.IntegerField(default=0)),
                ('vector_ids', models.JSONField(blank=True, default=list, help_text='IDs des vecteurs dans la base vectorielle')),
                ('referenced_count', models.IntegerField(default=0, verbose_name='Nombre de références')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_legislation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document législatif',
                'verbose_name_plural': 'Documents législatifs',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='ValidationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Approuvé'), ('reject', 'Rejeté'), ('flag', 'Signalé'), ('request_more', "Demander plus d'info")], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('ai_assisted', models.BooleanField(default=False)),
                ('ai_recommendation_followed', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_decisions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_history', to='users.document')),
            ],
            options={
                'verbose_name': 'Décision de validation',
                'verbose_name_plural': 'Décisions de validation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'status'], name='users_docum_user_id_27ffc0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'uploaded_at'], name='users_docum_status_26d218_idx'),
        ),
        migrations.AddIndex(
            model_name='legislationdocument',
            index=models.Index(fields=['country', 'category'], name='users_legis_country_80d204_idx'),
        ),
        migrations.AddIndex(
            model_name='legislationdocument',
            index=models.Index(fields=['indexed', 'is_active'], name='users_legis_indexed_e7c08e_idx'),
        ),
    ]
