# Generated by Django 5.1.2 on 2026-01-05 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_uploadeddocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_score', models.BooleanField(default=True, verbose_name='Alertes de score')),
                ('notifications_recommendations', models.BooleanField(default=True, verbose_name='Recommandations')),
                ('notifications_documents', models.BooleanField(default=True, verbose_name='Documents requis')),
                ('two_factor_auth', models.BooleanField(default=False, verbose_name='Authentification à deux facteurs')),
                ('data_sharing', models.BooleanField(default=False, verbose_name='Partage de données anonyme')),
                ('theme', models.CharField(choices=[('dark', 'Sombre'), ('light', 'Clair'), ('auto', 'Automatique')], default='dark', max_length=10, verbose_name='Thème')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5, verbose_name='Langue')),
                ('currency', models.CharField(choices=[('XAF', 'FCFA (XAF)'), ('EUR', 'EUR (€)'), ('USD', 'USD ($)')], default='XAF', max_length=3, verbose_name='Devise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Paramètres utilisateur',
                'verbose_name_plural': 'Paramètres utilisateurs',
                'db_table': 'user_settings',
            },
        ),
    ]
